# Generated by Django 5.1.4 on 2025-01-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_thumbnail', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('project_description', models.TextField()),
                ('tools', models.JSONField(default=list)),
            ],
        ),
    ]
