# Generated by Django 5.1.4 on 2025-01-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_thumbnail',
            field=models.ImageField(upload_to='project_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tools',
            field=models.JSONField(default=list, null=True),
        ),
    ]
