# Generated by Django 5.1.4 on 2025-01-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_bio_description_alter_bio_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tools',
        ),
    ]
